INSERT INTO menu_items (name, food_description, price, item_url, type_of_item)
  VALUES
  ('Phở Đặc Biệt', 'Rare beef, flank, tendon, tripe, beefball', 1500, '/docs/food-images/house-special.jpeg', 'main'),
  ('Phở tái', 'Rare beef, beefball', 1300, '/docs/food-images/pho2.jpeg', 'main'),
  ('Phở satế bò', 'Spicy peanut sate soup, rare beef or chicken', 1600, '/docs/food-images/pho3.jpeg', 'main'),
  ('Phở Fettuccine', 'Fettuccine noodles, special sauce', 1800, '/docs/food-images/italian2.jpeg', 'main'),
  ('Phở noodles with Meat Sauce', 'Noodles, meat sauce', 1700, '/docs/food-images/italian3.jpeg', 'main'),
  ('Phở Lasagne', 'Oven baked Phở noodles with ricotta cheese, tomato sauce', 2000, '/docs/food-images/italian4.jpeg', 'main'),
  ('Phở Seafood', 'Shrimp, squid, crabstick, vegetable', 1800, '/docs/food-images/seafood-pho.jpeg', 'main'),
  ('Phở Vegetarian', 'Vegetable and tofu, fried shallots', 1800, '/docs/food-images/vegetarian-pho.jpeg', 'main'),
  ('Muffuletta Sandwich', 'Deli meats, cheese with olive spread', 800, '/docs/food-images/Muffuletta.webp', 'sandwich'),
  ('Mini Italian Meatball Sliders', 'Cheesy meatballs, roasted peppers', 700, '/docs/food-images/Meatball-Sliders.webp', 'sandwich'),
  ('Porchetta Sandwich', 'Pork shoulder, rosemary, fennel and garlic', 900, '/docs/food-images/Porchetta-Sandwich.webp', 'sandwich'),
  ('Meatball Grilled Cheese Sandwich', 'Meatball and cheese', 800, '/docs/food-images/Meatball-Smash-Grilled-Cheese.webp', 'sandwich'),
  ('Tomato Basil Soup', 'Tomato and Basil', 500, '/docs/food-images/Basil-Tomato.jpeg', 'soup'),
  ('Ravioli Phở Soup', 'Very hearty', 500, '/docs/food-images/Ravioli-pho broth.jpeg', 'soup'),
  ('Meatball Phở Soup', 'Very hearty + Meatball', 500, '/docs/food-images/Meatball-pho-soup.jpeg', 'soup'),
  ('Saigon beer', '355ml', 900, '/docs/food-images/saigon.jpeg', 'drink'),
  ('Buddha beer', '330ml', 900, '/docs/food-images/buddha.jpeg', 'drink'),
  ('Peroni beer', '330ml', 900, '/docs/food-images/peroni.jpeg', 'drink'),
  ('Birra Moretti beer', '330ml', 1000, '/docs/food-images/birra.jpeg', 'drink'),
  ('Assorted pop', '330ml', 400, '/docs/food-images/pop.jpeg', 'drink'),
  ('Vietnamese Italian coffee', 'Cold Italian coffee with condensed milk', 600, '/docs/food-images/coffee.jpeg', 'drink'),
  ('Taro Bubble Tea', 'one size', 560, '/docs/food-images/taro.jpeg', 'bubbletea'),
  ('Mango Bubble Tea', 'one size', 550, '/docs/food-images/mango.jpeg', 'bubbletea'),
  ('Peach Bubble Tea', 'one size', 560, '/docs/food-images/peach.png', 'bubbletea'),
  ('Durian Bubble Tea', 'one size', 700, '/docs/food-images/durian.webp', 'bubbletea'),
  ('Lychee Bubble Tea', 'one size', 560, '/docs/food-images/lychee.png', 'bubbletea'),
  ('Italian Sorbet', 'Apple, Berry, Melon, Coconut', 500, '/docs/food-images/sorbet.jpeg', 'dessert'),
  ('Ice cream waffle cone', 'Vanilla, Strawberry, Mango, Chocolate, Durian', 500, '/docs/food-images/wafflecone.jpeg', 'dessert');
